version: 2.1

connections:
  - source_config:
      name: "Google Sheets - Finance Budget"
      source_definition_name: "Google Sheets"
      spreadsheet_id: "https://docs.google.com/spreadsheets/d/1u3GeuW1qQUnLWiD5cXQeU91PKRGQRcW-P6bSZDQplMw"
      row_batch_size: 200
      prefix: "finance__"

    destination_config:
      source_definition_name: "BigQuery"
      source_name: "BigQuery - Google Sheets"

    connection_config:
      namespace_definition: source
      namespace_format: "${SOURCE_NAMESPACE}"
      streams:
        budget: "full_refresh|append"

  - source_config:
      name: "Google Sheets - Finance Stock Ledger"
      source_definition_name: "Google Sheets"
      spreadsheet_id: "https://docs.google.com/spreadsheets/d/1hR11_dNuq6liXqYoa9tlpm5egMdTKRffIRwC5ZVxsEg"
      row_batch_size: 200
      prefix: "finance__"

    destination_config:
      source_definition_name: "BigQuery"
      source_name: "BigQuery - Google Sheets"

    connection_config:
      namespace_definition: netsuite_stock_ledger
      namespace_format: "${SOURCE_NAMESPACE}"
      streams:
        budget: "full_refresh|append"
  
  - source_config:
      name: "Google Sheets - Flexport Shipments"
      source_definition_name: "Google Sheets"
      spreadsheet_id: "https://docs.google.com/spreadsheets/d/1FxejNWsoBYmvoYzllaWYyYZ326Hyc5p6X8tehjbEn2U"
      row_batch_size: 200
      prefix: "gsheet_flexport__"

    destination_config:
      source_definition_name: "S3"
      s3_bucket_name_prefix: "heroes-dl-silver"

    connection_config:
      namespace_definition: source
      namespace_format: "${SOURCE_NAMESPACE}"
      streams:
        raw: "full_refresh|overwrite"
    
  - source_config:
      name: "Google Sheets - Flexport Billing"
      source_definition_name: "Google Sheets"
      spreadsheet_id: "https://docs.google.com/spreadsheets/d/1TnEm1sAJTQEZ6yWRTRlaqlJqL9gPEAWOddUC2WwhOqQ"
      row_batch_size: 200
      prefix: "gsheet_flexport__"

    destination_config:
      source_definition_name: "S3"
      s3_bucket_name_prefix: "heroes-dl-silver"

    connection_config:
      namespace_definition: source
      namespace_format: "${SOURCE_NAMESPACE}"
      streams:
        raw: "full_refresh|overwrite"
